-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.app_key_links ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.skill_app_links ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS set_app_key_links_updated_at ON public.app_key_links;
CREATE TRIGGER set_app_key_links_updated_at BEFORE UPDATE ON public.app_key_links
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_skill_app_links_updated_at ON public.skill_app_links;
CREATE TRIGGER set_skill_app_links_updated_at BEFORE UPDATE ON public.skill_app_links
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

