/**
 * 此文件由 Meoo Cloud 自动生成并管理。严禁手动修改、覆盖或重新创建；云服务初始化、关联或恢复时会重新生成此文件。业务代码只能导入和使用本文件导出的内容。
 *
 * This file is automatically generated and managed by Meoo Cloud.
 * DO NOT edit, overwrite, or recreate it manually. Only import and use its exports.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { CLOUD_ENV } from './cloud-env.generated';

export const projectUrlId = CLOUD_ENV.projectUrlId;
export const supabaseUrl = CLOUD_ENV.supabaseUrl;
export const supabaseAnonKey = CLOUD_ENV.supabaseAnonKey;

export function getSupabaseUrl(): string {
  return supabaseUrl;
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: projectUrlId ? { 'OneDay-App-Id': projectUrlId } : {},
  },
});
