/**
 * 此文件由 Meoo Cloud 自动生成并管理，会在云服务初始化、关联、恢复或发布时按环境重写。
 * 严禁手动修改、覆盖或重新创建；业务代码只能从 './client' 导入使用。
 *
 * This file is automatically generated and managed by Meoo Cloud and is
 * rewritten per environment on preview/publish. DO NOT edit, overwrite, or
 * recreate it manually.
 */

export const CLOUD_ENV = {
  supabaseUrl: "https://yhqzletzhzij4sax.database.meoo.xyz",
  supabaseAnonKey: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg0OTYzODAyLCJleHAiOjEzMjk1NjAzODAyfQ.oIQw3VwGvHtSAXySDts-P2oKRGScqnIOqEDjDiYJqKI",
  projectUrlId: "wgh68uu2zihu",
} as const;
