/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAppsRouteImport } from './routes/_app/apps'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppKeysRouteImport } from './routes/_app/keys'
import { Route as AppMineRouteImport } from './routes/_app/mine'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps.$appId'
import { Route as AppAppsNewRouteImport } from './routes/_app/apps.new'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app/assets.$assetId'
import { Route as AppAssetsNewRouteImport } from './routes/_app/assets.new'
import { Route as AppKeysKeyIdRouteImport } from './routes/_app/keys.$keyId'
import { Route as AppSkillsSkillIdRouteImport } from './routes/_app/skills.$skillId'
import { Route as AppAppsAppIdEditRouteImport } from './routes/_app/apps.$appId.edit'
import { Route as AppAssetsAssetIdEditRouteImport } from './routes/_app/assets.$assetId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/apps.lazy').then((d) => d.Route))
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/assets.lazy').then((d) => d.Route))
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/keys.lazy').then((d) => d.Route))
const AppMineRoute = AppMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/mine.lazy').then((d) => d.Route))
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/skills.lazy').then((d) => d.Route))
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppAppsRoute,
} as any)
const AppAppsNewRoute = AppAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAppsRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppKeysKeyIdRoute = AppKeysKeyIdRouteImport.update({
  id: '/$keyId',
  path: '/$keyId',
  getParentRoute: () => AppKeysRoute,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/$skillId',
  path: '/$skillId',
  getParentRoute: () => AppSkillsRoute,
} as any)
const AppAppsAppIdEditRoute = AppAppsAppIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAssetsAssetIdEditRoute = AppAssetsAssetIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAssetsAssetIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/apps': typeof AppAppsRouteWithChildren
  '/assets': typeof AppAssetsRouteWithChildren
  '/keys': typeof AppKeysRouteWithChildren
  '/mine': typeof AppMineRoute
  '/skills': typeof AppSkillsRouteWithChildren
  '/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/apps/new': typeof AppAppsNewRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRouteWithChildren
  '/assets/new': typeof AppAssetsNewRoute
  '/keys/$keyId': typeof AppKeysKeyIdRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/apps': typeof AppAppsRouteWithChildren
  '/assets': typeof AppAssetsRouteWithChildren
  '/keys': typeof AppKeysRouteWithChildren
  '/mine': typeof AppMineRoute
  '/skills': typeof AppSkillsRouteWithChildren
  '/': typeof AppIndexRoute
  '/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/apps/new': typeof AppAppsNewRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRouteWithChildren
  '/assets/new': typeof AppAssetsNewRoute
  '/keys/$keyId': typeof AppKeysKeyIdRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/apps': typeof AppAppsRouteWithChildren
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/keys': typeof AppKeysRouteWithChildren
  '/_app/mine': typeof AppMineRoute
  '/_app/skills': typeof AppSkillsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/_app/apps/new': typeof AppAppsNewRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRouteWithChildren
  '/_app/assets/new': typeof AppAssetsNewRoute
  '/_app/keys/$keyId': typeof AppKeysKeyIdRoute
  '/_app/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/_app/apps/$appId/edit': typeof AppAppsAppIdEditRoute
  '/_app/assets/$assetId/edit': typeof AppAssetsAssetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apps'
    | '/assets'
    | '/keys'
    | '/mine'
    | '/skills'
    | '/apps/$appId'
    | '/apps/new'
    | '/assets/$assetId'
    | '/assets/new'
    | '/keys/$keyId'
    | '/skills/$skillId'
    | '/apps/$appId/edit'
    | '/assets/$assetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/apps'
    | '/assets'
    | '/keys'
    | '/mine'
    | '/skills'
    | '/'
    | '/apps/$appId'
    | '/apps/new'
    | '/assets/$assetId'
    | '/assets/new'
    | '/keys/$keyId'
    | '/skills/$skillId'
    | '/apps/$appId/edit'
    | '/assets/$assetId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/apps'
    | '/_app/assets'
    | '/_app/keys'
    | '/_app/mine'
    | '/_app/skills'
    | '/_app/'
    | '/_app/apps/$appId'
    | '/_app/apps/new'
    | '/_app/assets/$assetId'
    | '/_app/assets/new'
    | '/_app/keys/$keyId'
    | '/_app/skills/$skillId'
    | '/_app/apps/$appId/edit'
    | '/_app/assets/$assetId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mine': {
      id: '/_app/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof AppMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId': {
      id: '/_app/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppAppsRoute
    }
    '/_app/apps/new': {
      id: '/_app/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppAppsNewRouteImport
      parentRoute: typeof AppAppsRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/assets/new': {
      id: '/_app/assets/new'
      path: '/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/keys/$keyId': {
      id: '/_app/keys/$keyId'
      path: '/$keyId'
      fullPath: '/keys/$keyId'
      preLoaderRoute: typeof AppKeysKeyIdRouteImport
      parentRoute: typeof AppKeysRoute
    }
    '/_app/skills/$skillId': {
      id: '/_app/skills/$skillId'
      path: '/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppSkillsRoute
    }
    '/_app/apps/$appId/edit': {
      id: '/_app/apps/$appId/edit'
      path: '/edit'
      fullPath: '/apps/$appId/edit'
      preLoaderRoute: typeof AppAppsAppIdEditRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/assets/$assetId/edit': {
      id: '/_app/assets/$assetId/edit'
      path: '/edit'
      fullPath: '/assets/$assetId/edit'
      preLoaderRoute: typeof AppAssetsAssetIdEditRouteImport
      parentRoute: typeof AppAssetsAssetIdRoute
    }
  }
}

interface AppAppsAppIdRouteChildren {
  AppAppsAppIdEditRoute: typeof AppAppsAppIdEditRoute
}

const AppAppsAppIdRouteChildren: AppAppsAppIdRouteChildren = {
  AppAppsAppIdEditRoute: AppAppsAppIdEditRoute,
}

const AppAppsAppIdRouteWithChildren = AppAppsAppIdRoute._addFileChildren(
  AppAppsAppIdRouteChildren,
)

interface AppAppsRouteChildren {
  AppAppsAppIdRoute: typeof AppAppsAppIdRouteWithChildren
  AppAppsNewRoute: typeof AppAppsNewRoute
}

const AppAppsRouteChildren: AppAppsRouteChildren = {
  AppAppsAppIdRoute: AppAppsAppIdRouteWithChildren,
  AppAppsNewRoute: AppAppsNewRoute,
}

const AppAppsRouteWithChildren =
  AppAppsRoute._addFileChildren(AppAppsRouteChildren)

interface AppAssetsAssetIdRouteChildren {
  AppAssetsAssetIdEditRoute: typeof AppAssetsAssetIdEditRoute
}

const AppAssetsAssetIdRouteChildren: AppAssetsAssetIdRouteChildren = {
  AppAssetsAssetIdEditRoute: AppAssetsAssetIdEditRoute,
}

const AppAssetsAssetIdRouteWithChildren =
  AppAssetsAssetIdRoute._addFileChildren(AppAssetsAssetIdRouteChildren)

interface AppAssetsRouteChildren {
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRouteWithChildren
  AppAssetsNewRoute: typeof AppAssetsNewRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsAssetIdRoute: AppAssetsAssetIdRouteWithChildren,
  AppAssetsNewRoute: AppAssetsNewRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppKeysRouteChildren {
  AppKeysKeyIdRoute: typeof AppKeysKeyIdRoute
}

const AppKeysRouteChildren: AppKeysRouteChildren = {
  AppKeysKeyIdRoute: AppKeysKeyIdRoute,
}

const AppKeysRouteWithChildren =
  AppKeysRoute._addFileChildren(AppKeysRouteChildren)

interface AppSkillsRouteChildren {
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
}

const AppSkillsRouteChildren: AppSkillsRouteChildren = {
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
}

const AppSkillsRouteWithChildren = AppSkillsRoute._addFileChildren(
  AppSkillsRouteChildren,
)

interface AppRouteChildren {
  AppAppsRoute: typeof AppAppsRouteWithChildren
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppKeysRoute: typeof AppKeysRouteWithChildren
  AppMineRoute: typeof AppMineRoute
  AppSkillsRoute: typeof AppSkillsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppsRoute: AppAppsRouteWithChildren,
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppKeysRoute: AppKeysRouteWithChildren,
  AppMineRoute: AppMineRoute,
  AppSkillsRoute: AppSkillsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
